In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

sns.set_theme()

In [15]:
df_2 =pd.read_csv('titlemeta.tsv', sep='\t', dtype=str)
hathi_metadata = df_2
# df = pd.read_parquet('final_merged.parquet')

In [16]:
df = pd.read_parquet('final_merged.parquet')

In [17]:
df.head()

                                  mention_id    term  \
book_id             character_id
chi.086202240.clean 0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts

                                                                           sentence  \
book_id             character_id
chi.086202240.clean 0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...

                                  start_idx  end_idx  sentence_start_idx  \
book_id             character_id
chi.086202240.clean 0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200

                                  sentence_end_idx adjectives_fashion  \
book_id             character_id
chi.086202240.clean 0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []

                                  character_start_idx  character_end_idx  \
book_id             character_id
chi.086202240.clean 0                          4230.0             4231.0
                    0                          4209.0             4210.0
                    0                          4254.0             4255.0
                    0                          4154.0             4156.0
                    0                          4334.0             4336.0

                                 gender_local_pron all_genders  \
book_id             character_id
chi.086202240.clean 0                         None        None
                    0                         None        None
                    0                         None        None
                    0                         None        None
                    0                         None        None

                                 gender_dep_pron  \
book_id             character_id
chi.086202240.clean 0                       None
                    0                       None
                    0                       None
                    0                       None
                    0                       None

                                                                    adjectives_char  \
book_id             character_id
chi.086202240.clean 0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...

                                 gender_booknlp  inferreddate  decade
book_id             character_id
chi.086202240.clean 0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0

In [18]:
df.dtypes

mention_id               int64
term                    object
sentence                object
start_idx                int64
end_idx                  int64
sentence_start_idx       int64
sentence_end_idx         int64
adjectives_fashion      object
character_start_idx    float64
character_end_idx      float64
gender_local_pron       object
all_genders             object
gender_dep_pron         object
adjectives_char         object
gender_booknlp          object
inferreddate           float64
decade                 float64
dtype: object

In [19]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [20]:
# df.applymap(lambda x: isinstance(x, (list, tuple, dict, np.ndarray))).any()

In [21]:
df_clean = df.drop_duplicates(subset=["term", "sentence"])

In [22]:
df_clean.head()

                                  mention_id      term  \
book_id             character_id
chi.086202240.clean 0               17370773    shorts
                    218             17370789  covering
                    218             17370790   topcoat
                    0               17370796     shirt
                    0               17370799  covering

                                                                           sentence  \
book_id             character_id
chi.086202240.clean 0             How long I remained in shorts I cannot novembe...
                    218           Instantly I knew \nthat in order to assuage hi...
                    218           Instantly I knew \nthat in order to assuage hi...
                    0             Knowing in my own mind that \nmy shirt which I...
                    0             Knowing in my own mind that \nmy shirt which I...

                                  start_idx  end_idx  sentence_start_idx  \
book_id             character_id
chi.086202240.clean 0                    23       29                4200
                    218                 318      326               20869
                    218                 334      341               20869
                    0                    32       37               29540
                    0                   329      337               29540

                                  sentence_end_idx adjectives_fashion  \
book_id             character_id
chi.086202240.clean 0                         4409                 []
                    218                      21292             [thin]
                    218                      21292                 []
                    0                        29900                 []
                    0                        29900            [clean]

                                  character_start_idx  character_end_idx  \
book_id             character_id
chi.086202240.clean 0                          4230.0             4231.0
                    218                       21199.0            21202.0
                    218                       21199.0            21202.0
                    0                         29569.0            29571.0
                    0                         29814.0            29816.0

                                 gender_local_pron  \
book_id             character_id
chi.086202240.clean 0                         None
                    218                       male
                    218                       male
                    0                         None
                    0                         None

                                                                        all_genders  \
book_id             character_id
chi.086202240.clean 0                                                          None
                    218           {'female': None, 'male': ['his', 'he'], 'nonbi...
                    218           {'female': None, 'male': ['his', 'he'], 'nonbi...
                    0                                                          None
                    0                                                          None

                                 gender_dep_pron  \
book_id             character_id
chi.086202240.clean 0                       None
                    218                     None
                    218                     male
                    0                       None
                    0                       None

                                                                    adjectives_char  \
book_id             character_id
chi.086202240.clean 0             [more, content, gay, aged, faithful, astonishe...
                    218                                                [Honourable]
                    218                                                [Honourable]
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...

                                 gender_booknlp  inferreddate  decade
book_id             character_id
chi.086202240.clean 0                he/him/his        1886.0   188.0
                    218              he/him/his        1886.0   188.0
                    218              he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0

In [23]:
df.columns

Index(['mention_id', 'term', 'sentence', 'start_idx', 'end_idx',
       'sentence_start_idx', 'sentence_end_idx', 'adjectives_fashion',
       'character_start_idx', 'character_end_idx', 'gender_local_pron',
       'all_genders', 'gender_dep_pron', 'adjectives_char', 'gender_booknlp',
       'inferreddate', 'decade'],
      dtype='object')

In [24]:
df.columns = df.columns.str.strip()  # remove leading/trailing whitespace

In [25]:
df.head()

                                  mention_id    term  \
book_id             character_id
chi.086202240.clean 0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts

                                                                           sentence  \
book_id             character_id
chi.086202240.clean 0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...

                                  start_idx  end_idx  sentence_start_idx  \
book_id             character_id
chi.086202240.clean 0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200

                                  sentence_end_idx adjectives_fashion  \
book_id             character_id
chi.086202240.clean 0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []

                                  character_start_idx  character_end_idx  \
book_id             character_id
chi.086202240.clean 0                          4230.0             4231.0
                    0                          4209.0             4210.0
                    0                          4254.0             4255.0
                    0                          4154.0             4156.0
                    0                          4334.0             4336.0

                                 gender_local_pron all_genders  \
book_id             character_id
chi.086202240.clean 0                         None        None
                    0                         None        None
                    0                         None        None
                    0                         None        None
                    0                         None        None

                                 gender_dep_pron  \
book_id             character_id
chi.086202240.clean 0                       None
                    0                       None
                    0                       None
                    0                       None
                    0                       None

                                                                    adjectives_char  \
book_id             character_id
chi.086202240.clean 0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...

                                 gender_booknlp  inferreddate  decade
book_id             character_id
chi.086202240.clean 0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0

In [26]:
# hathi_metadata = pd.read_csv("../data/hathimeta/titlemeta.tsv", sep="\t")
hathi_metadata.loc[:, "book_id"] = hathi_metadata.docid.apply(lambda x: x + ".clean")
hathi_metadata = hathi_metadata.set_index("book_id")

In [27]:
df.head()

                                  mention_id    term  \
book_id             character_id
chi.086202240.clean 0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts

                                                                           sentence  \
book_id             character_id
chi.086202240.clean 0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...

                                  start_idx  end_idx  sentence_start_idx  \
book_id             character_id
chi.086202240.clean 0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200

                                  sentence_end_idx adjectives_fashion  \
book_id             character_id
chi.086202240.clean 0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []

                                  character_start_idx  character_end_idx  \
book_id             character_id
chi.086202240.clean 0                          4230.0             4231.0
                    0                          4209.0             4210.0
                    0                          4254.0             4255.0
                    0                          4154.0             4156.0
                    0                          4334.0             4336.0

                                 gender_local_pron all_genders  \
book_id             character_id
chi.086202240.clean 0                         None        None
                    0                         None        None
                    0                         None        None
                    0                         None        None
                    0                         None        None

                                 gender_dep_pron  \
book_id             character_id
chi.086202240.clean 0                       None
                    0                       None
                    0                       None
                    0                       None
                    0                       None

                                                                    adjectives_char  \
book_id             character_id
chi.086202240.clean 0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...

                                 gender_booknlp  inferreddate  decade
book_id             character_id
chi.086202240.clean 0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0

In [28]:
# Step 0: delete any old arrays to avoid stale data
for var in ["genders", "features", "decades", "orig_indices"]:
    if var in globals():
        del globals()[var]

In [29]:
genders = []
features = []
decades = []
orig_indices = []

subset = df_clean.dropna(subset=["gender_dep_pron"])

for row in subset.itertuples():
    if row.gender_dep_pron[0] in ("t", "z", "n", "o"):
        continue
    adjs = [adj for adj in row.adjectives_fashion if adj is not None]

    if len(adjs) == 0:
        continue

    adjs_2 = [adj for adj in row.adjectives_char if adj is not None]


    # append consistently
    genders.append(row.gender_dep_pron)
    # features.append([f"term_{row.term.lower()}"])
    features.append(
    [f"term_{row.term.lower()}"] +
    [f"adj_f_{adj.lower()}" for adj in adjs] + [f"adj_c_{adj.lower()}" for adj in adjs_2]
)

    decades.append(row.decade)
    orig_indices.append(row.Index)

In [30]:
print(len(features), len(genders), len(decades), len(orig_indices))

250391 250391 250391 250391

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score




encoder = CountVectorizer(
    input="content",
    lowercase=False,
    preprocessor=None,
    tokenizer=lambda x: x,
    min_df=20,
)
encoder.fit(features)

le = LabelEncoder()
le.fit(genders)


def get_features(split):
    split_g = []
    split_f = []
    for i in split:
        split_g.append(genders[i])
        split_f.append(features[i])
    return split_g, split_f


def train_classifier(split):
    genders, features = get_features(split)
    X = encoder.transform(features)
    y = le.transform(genders)
    model = LogisticRegression(penalty="l1", solver="liblinear")
    model.fit(X, y)

    print(f1_score(y[:1000], model.predict(X[:1000])))

    # print(model.score(X[:1000], y[:1000]))
    return model

/Library/Python/3.9/site-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [126]:
    coef = model.coef_[0]
    feature_names = encoder.get_feature_names_out()
    feature_importance = pd.Series(np.abs(coef), index=feature_names).sort_values(ascending=False)

    print("\nTop 20 important features:")
    print(feature_importance.head(20))

Top 20 important features:
term_bodice         5.151799
adj_f_clerical      5.083184
adj_f_mannish       5.038056
adj_c_beautifull    4.961527
term_skirt          4.936520
term_overcoat       4.841564
term_waistcoat      4.785828
term_sunbonnet      4.458060
term_cassock        4.422065
term_muff           4.315643
adj_c_inimitable    4.296796
term_pipe           4.103576
term_skirts         4.027251
term_flannels       3.953860
adj_c_beneficent    3.910021
term_trousseau      3.759623
term_braids         3.725152
adj_c_oppressed     3.716552
term_petticoat      3.690063
term_dresses        3.655540
dtype: float64

In [45]:
le.classes_

array(['female', 'male'], dtype='<U6')

In [46]:
len(genders), len(features), len(decades), len(orig_indices)

(250391, 250391, 250391, 250391)

In [47]:
models = []
for decade in range(180, 192):
    print(decade)
    split = np.where(np.array(decades) == decade)[0]
    model = train_classifier(split)
    models.append(model)

180
0.915057915057915
181
0.9129373474369405
182
0.936986301369863
183
0.9191430545957153
184
0.9066478076379066
185
0.9013632718524459
186
0.8955465587044534
187
0.8653421633554084
188
0.8496993987975952
189
0.8610871440897325
190
0.8411016949152542
191
0.8814691151919867

In [48]:
def _():
    for i, decade in enumerate(range(180, 192)):
        print("======", decade, "=======")
        model = models[i]
        features = encoder.get_feature_names_out()
        k = 10

        print(le.classes_[1])
        for i in model.coef_.argsort()[0, -k:][::-1]:
            print(f"{features[i]}\t{model.coef_[0, i]}")

        print()

        print(le.classes_[0])
        for i in model.coef_.argsort()[0, :k]:
            print(f"{features[i]}\t{model.coef_[0, i]}")


_()

====== 180 =======
male
term_coat	2.7985548825156927
term_cap	1.4349533229451277
adj_c_absent	1.3741220508439125
adj_c_empty	1.3358206041967744
adj_c_such	1.2740678385256023
adj_c_right	1.2460301450678408
adj_c_fortunate	1.1020144036880741
term_waistcoat	1.0514337679690506
term_hat	0.9717953731394535
term_breeches	0.8706997929205307

female
adj_c_charitable	-2.5195119089168143
term_attire	-2.1972702579703296
term_apron	-2.1892059688417933
term_gloves	-1.92621456233411
adj_f_fine	-1.598109248130465
adj_f_royal	-1.540951002298528
term_robe	-1.439282093855438
adj_c_loath	-1.38219750889781
term_hands	-1.3547629946385433
adj_c_charming	-1.2927428455644476
====== 181 =======
male
term_coat	3.6497751500802957
term_uniform	2.0388740095903928
adj_c_equal	1.9814993661082498
term_wig	1.941392269492842
term_shirt	1.9340841057662357
adj_c_selfish	1.9088030759270591
term_waistcoat	1.758998760473541
adj_c_bankrupt	1.5572807065477468
adj_f_mean	1.5323896928894827
adj_c_interested	1.3990400966299488

female
term_veil	-3.2431087407922954
term_petticoat	-2.4762207168632226
adj_c_thunderstruck	-2.400480153631814
term_caps	-1.8773847343836993
adj_c_religious	-1.7969483553518928
adj_f_close	-1.7676451332662269
term_bonnet	-1.717140394124468
term_gown	-1.6500054594405122
adj_c_distressed	-1.606761196677908
adj_f_rich	-1.5839072695700454
====== 182 =======
male
adj_f_strange	3.3110264822886117
term_suit	3.0692705579047
adj_c_wicked	2.957517821024756
adj_f_military	2.943926544851456
term_boots	2.938947268077647
term_breeches	2.631579691304293
term_coat	2.6173659929621627
term_waistcoat	2.4634073129611327
adj_c_unarmed	2.4282536241398436
term_uniform	2.3934617386993104

female
term_veil	-6.345416983034151
term_petticoat	-4.027556263163017
term_shawl	-3.1690390294585686
term_dresses	-2.9279591307808928
adj_c_fitful	-2.865125225777355
term_petticoats	-2.842546616160385
adj_c_frolicsome	-2.841729429675071
term_coif	-2.8094041721482905
adj_f_masculine	-2.6858375617332735
adj_c_rueful	-2.6365673203443962
====== 183 =======
male
adj_f_shaggy	4.549884873258111
term_waistcoat	3.8610905918911254
term_coat	3.759698736443467
term_uniform	3.717459704573679
adj_f_military	3.677902451109774
term_breeches	3.1984741421598106
adj_c_lowborn	3.1112509047387595
term_doublet	3.0898790502976468
term_boots	2.8979187920394085
term_shirt	2.65783213018619

female
term_petticoat	-4.09120766622042
adj_c_discourteous	-3.6762611092043227
term_dresses	-3.4080024053599733
term_shawl	-3.317476246866209
term_veil	-3.2870247697814765
term_laces	-2.7721411304790182
adj_c_desirable	-2.736684055649453
term_coif	-2.68584436877323
adj_c_barefoot	-2.6779287468154336
adj_f_pink	-2.641808383124768
====== 184 =======
male
term_shirt	4.576969639198141
term_cravat	4.285072430019514
adj_f_threadbare	4.027782134620282
term_coat	3.6251577905378043
term_waistcoat	3.6062547094482023
adj_f_clerical	3.286809568063985
adj_c_overcome	3.234001501289357
term_pantaloons	3.1277558774788092
term_boots	3.0965040895264453
term_uniform	2.988215068402421

female
term_veil	-4.450673255154722
term_shawl	-4.381883606951567
adj_c_mansworn	-4.134283642518491
term_petticoat	-3.514063933719858
term_dresses	-3.5002917193813405
term_stays	-3.4721236580719816
adj_f_pretty	-3.0315744132295555
term_bodice	-2.987256877636152
term_laces	-2.9587469041466488
adj_f_bridal	-2.950042033171887
====== 185 =======
male
term_beaver	5.745397903152285
term_waistcoat	4.792744940325346
term_coat	4.570918618082594
term_breeches	4.034180192469648
term_shirt	3.6773336963961074
adj_c_unspoiled	3.332503097289171
term_uniform	3.329950431967278
adj_c_livid	3.2501216759945506
adj_f_clerical	3.2494732117791454
term_pockets	3.2322112580627356

female
term_petticoat	-3.9018919893134574
term_skirts	-3.89706320950875
term_veil	-3.7481114322407088
term_farthingale	-3.4608590988978625
adj_c_meritorious	-3.346047375980279
term_shawl	-3.2259498286392176
adj_c_prudential	-3.140712362013031
adj_f_bridal	-2.9251783476713484
term_brocade	-2.8853557971354995
term_silk	-2.846090229380914
====== 186 =======
male
adj_f_military	4.212946534092435
term_waistcoat	3.9304652446461166
term_cravat	3.829827952622953
term_uniform	3.489897007552738
term_overcoat	3.3433383768936227
term_neckcloth	3.3285879570066603
adj_c_disrespectful	3.170797979863666
term_pantaloons	3.1345599564258886
term_shirt	3.131447259572567
adj_f_clerical	3.071924570467818

female
term_veil	-4.30074879604577
term_dresses	-4.1982950395905805
term_skirt	-3.875119173240611
term_petticoat	-3.772795809581431
adj_f_masculine	-3.461520566439293
adj_f_bridal	-3.4118493830076098
term_silk	-3.301522254469298
term_mantilla	-3.289872508049087
term_gowns	-3.2183070951044277
term_bodice	-3.1422906739399563
====== 187 =======
male
term_waistcoat	4.910745413290605
term_cassock	4.036698679443758
term_blouse	3.7952187470394145
term_cravat	3.7200789099606246
term_overcoat	3.6694043104242304
term_surplice	3.5742010285815584
adj_f_official	3.500051664199183
term_breeches	3.467835169873442
term_shirt	3.357658241068503
adj_c_ungraceful	3.3328965891668685

female
term_silk	-4.808754693052943
term_braids	-4.523403887915847
term_veil	-3.924992955173455
term_dresses	-3.7317500743054697
adj_c_portionless	-3.69133454409267
adj_f_bridal	-3.6541185776973326
term_gowns	-3.4166135631399777
term_shawl	-3.3863002690465485
term_petticoat	-3.273723342822364
term_skirts	-3.159754339671061
====== 188 =======
male
term_waistcoat	5.324620384952788
term_overcoat	4.614463884101645
adj_c_ghostlike	3.961936942848772
term_uniform	3.8579581613039626
term_flannels	3.7835987130544786
term_gaiters	3.738355102239722
term_cravat	3.633464585587676
term_breeches	3.5502011981269836
adj_f_clerical	3.4789998317825015
term_nightshirt	3.329779831590017

female
adj_c_untutored	-4.940488591658183
term_braids	-4.744308889615322
term_bodice	-4.077674043492393
term_silk	-3.901597310912793
term_dresses	-3.8309016662419326
term_shawl	-3.6942722775754118
term_veil	-3.6730161060343396
term_skirt	-3.5932421550002633
term_wrapper	-3.517137435490567
term_petticoat	-3.3072514128252912
====== 189 =======
male
term_waistcoat	5.543925999218425
adj_f_clerical	4.6910156754730785
term_breeches	4.568940717002893
term_overcoat	4.443286856059438
term_surplice	4.412951036623222
term_cassock	4.2789505705639606
term_cravat	4.208748170057281
term_neckcloth	3.7693038293386483
term_doublet	3.7280333690767846
term_greatcoat	3.518869452583168

female
term_laces	-5.136974633048032
term_bodice	-4.977991217044366
term_gowns	-4.711241850647916
term_braids	-4.3722849936075985
adj_f_bridal	-4.15135315354934
term_skirt	-4.141087565951778
adj_f_semitransparent	-4.097544386110682
term_veil	-4.097217440706269
term_farthingale	-4.0015007609365325
term_petticoat	-3.724109695506493
====== 190 =======
male
term_waistcoat	7.202324644106321
term_cravat	4.791535026788738
adj_f_clerical	4.597925304765333
term_buttonhole	4.045611698860964
term_cassock	3.9198014881112986
term_livery	3.8945987325106683
term_overcoat	3.770569131013674
term_tie	3.7640267951559725
term_neckcloth	3.746566173140511
adj_c_ornate	3.722007934662057

female
term_bodice	-5.964665559129751
term_gowns	-5.231363739136421
term_veil	-5.175947588952248
term_sunbonnet	-4.6541636337633845
adj_f_starry	-4.214695134612891
term_skirt	-4.13304296964965
term_dresses	-3.6358381240508884
term_braids	-3.593175218994951
term_trousseau	-3.5534333654106076
adj_f_shady	-3.51611453786303
====== 191 =======
male
adj_f_clerical	5.083183824248908
adj_c_beautifull	4.9615271318077445
term_overcoat	4.8415640316796
term_waistcoat	4.785827846337819
term_cassock	4.422064546902598
adj_c_inimitable	4.2967963468992965
term_pipe	4.1035762195347125
term_flannels	3.953859563486144
adj_c_beneficent	3.9100205828012835
term_greatcoat	3.5663062169316384

female
term_bodice	-5.151799236859485
adj_f_mannish	-5.03805613558267
term_skirt	-4.936520120414341
term_sunbonnet	-4.458060075218849
term_muff	-4.315642943479671
term_skirts	-4.027250859634516
term_trousseau	-3.759623253231015
term_braids	-3.7251515054685016
adj_c_oppressed	-3.7165516504745377
term_petticoat	-3.6900628393548756

In [49]:
# type(df['sentence'])  # should be pandas.core.series.Series
# df['sentence'].iloc[0]  # returns the string at first row

In [50]:
# type(df['sentence'])  # should be pandas.core.series.Series

In [51]:
df_clean

                                        mention_id      term  \
book_id                   character_id
chi.086202240.clean       0               17370773    shorts
                          218             17370789  covering
                          218             17370790   topcoat
                          0               17370796     shirt
                          0               17370799  covering
...                                            ...       ...
yale.39002030973185.clean 490              3121279   sleeves
                          0                3121284     trunk
                          0                3121292  uniforms
                          0                3121295     trunk
                          5597             3121296     shawl

                                                                                 sentence  \
book_id                   character_id
chi.086202240.clean       0             How long I remained in shorts I cannot novembe...
                          218           Instantly I knew \nthat in order to assuage hi...
                          218           Instantly I knew \nthat in order to assuage hi...
                          0             Knowing in my own mind that \nmy shirt which I...
                          0             Knowing in my own mind that \nmy shirt which I...
...                                                                                   ...
yale.39002030973185.clean 490           Occasionally we reached a group of \nbulbous y...
                          0             As I said before, it was a pleasure to under \...
                          0             I didn't \nknow exactly what I had done that w...
                          0             Might the small green trunk be sent immediatel...
                          5597          Might I take the portmanteau in one jinrikisha...

                                        start_idx  end_idx  \
book_id                   character_id
chi.086202240.clean       0                    23       29
                          218                 318      326
                          218                 334      341
                          0                    32       37
                          0                   329      337
...                                           ...      ...
yale.39002030973185.clean 490                 141      148
                          0                    68       73
                          0                   183      191
                          0                    22       27
                          5597                 67       72

                                        sentence_start_idx  sentence_end_idx  \
book_id                   character_id
chi.086202240.clean       0                           4200              4409
                          218                        20869             21292
                          218                        20869             21292
                          0                          29540             29900
                          0                          29540             29900
...                                                    ...               ...
yale.39002030973185.clean 490                       130067            130330
                          0                         131479            131648
                          0                         134880            135088
                          0                         135776            135867
                          5597                      135898            136017

                                       adjectives_fashion  \
book_id                   character_id
chi.086202240.clean       0                            []
                          218                      [thin]
                          218                          []
                          0                            []
                          0                       [clean]
...                                                   ...
yale.39002030973185.clean 490                          []
                          0                [green, small]
                          0                            []
                          0                [green, small]
                          5597                         []

                                        character_start_idx  \
book_id                   character_id
chi.086202240.clean       0                          4230.0
                          218                       21199.0
                          218                       21199.0
                          0                         29569.0
                          0                         29814.0
...                                                     ...
yale.39002030973185.clean 490                      130450.0
                          0                        131482.0
                          0                        135018.0
                          0                        135765.0
                          5597                     135950.0

                                        character_end_idx gender_local_pron  \
book_id                   character_id
chi.086202240.clean       0                        4231.0              None
                          218                     21202.0              male
                          218                     21202.0              male
                          0                       29571.0              None
                          0                       29816.0              None
...                                                   ...               ...
yale.39002030973185.clean 490                    130460.0              None
                          0                      131483.0              None
                          0                      135019.0              None
                          0                      135766.0              None
                          5597                   135960.0              None

                                                                              all_genders  \
book_id                   character_id
chi.086202240.clean       0                                                          None
                          218           {'female': None, 'male': ['his', 'he'], 'nonbi...
                          218           {'female': None, 'male': ['his', 'he'], 'nonbi...
                          0                                                          None
                          0                                                          None
...                                                                                   ...
yale.39002030973185.clean 490                                                        None
                          0                                                          None
                          0                                                          None
                          0                                                          None
                          5597                                                       None

                                       gender_dep_pron  \
book_id                   character_id
chi.086202240.clean       0                       None
                          218                     None
                          218                     male
                          0                       None
                          0                       None
...                                                ...
yale.39002030973185.clean 490                     None
                          0                       None
                          0                       None
                          0                       None
                          5597                    None

                                                                          adjectives_char  \
book_id                   character_id
chi.086202240.clean       0             [more, content, gay, aged, faithful, astonishe...
                          218                                                [Honourable]
                          218                                                [Honourable]
                          0             [more, content, gay, aged, faithful, astonishe...
                          0             [more, content, gay, aged, faithful, astonishe...
...                                                                                   ...
yale.39002030973185.clean 490           [little, more, sure, present, sorry, sure, sar...
                          0             [glad, afraid, native, richer, inhuman, sure, ...
                          0             [glad, afraid, native, richer, inhuman, sure, ...
                          0             [glad, afraid, native, richer, inhuman, sure, ...
                          5597          [glad, pleased, minded, able, helpless, sure, ...

                                       gender_booknlp  inferreddate  decade  \
book_id                   character_id
chi.086202240.clean       0                he/him/his        1886.0   188.0
                          218              he/him/his        1886.0   188.0
                          218              he/him/his        1886.0   188.0
                          0                he/him/his        1886.0   188.0
                          0                he/him/his        1886.0   188.0
...                                               ...           ...     ...
yale.39002030973185.clean 490                 she/her        1891.0   189.0
                          0                   she/her        1891.0   189.0
                          0                   she/her        1891.0   189.0
                          0                   she/her        1891.0   189.0
                          5597                she/her        1891.0   189.0

                                       adj_text
book_id                   character_id
chi.086202240.clean       0
                          218
                          218
                          0
                          0
...                                         ...
yale.39002030973185.clean 490
                          0
                          0
                          0
                          5597

[4864984 rows x 18 columns]

In [52]:
df['sentence']

book_id                    character_id
chi.086202240.clean        0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                                                                 ...
yale.39002030973185.clean  0               Might the small green trunk be sent immediatel...
                           5597            Might I take the portmanteau in one jinrikisha...
                           0               Might I take the portmanteau in one jinrikisha...
                           0               Might I take the portmanteau in one jinrikisha...
                           0               Might I take the portmanteau in one jinrikisha...
Name: sentence, Length: 17268825, dtype: object

In [53]:
df[['sentence']]

                                                                                 sentence
book_id                   character_id
chi.086202240.clean       0             How long I remained in shorts I cannot novembe...
                          0             How long I remained in shorts I cannot novembe...
                          0             How long I remained in shorts I cannot novembe...
                          0             How long I remained in shorts I cannot novembe...
                          0             How long I remained in shorts I cannot novembe...
...                                                                                   ...
yale.39002030973185.clean 0             Might the small green trunk be sent immediatel...
                          5597          Might I take the portmanteau in one jinrikisha...
                          0             Might I take the portmanteau in one jinrikisha...
                          0             Might I take the portmanteau in one jinrikisha...
                          0             Might I take the portmanteau in one jinrikisha...

[17268825 rows x 1 columns]

In [54]:
df.head()

                                  mention_id    term  \
book_id             character_id
chi.086202240.clean 0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts

                                                                           sentence  \
book_id             character_id
chi.086202240.clean 0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...

                                  start_idx  end_idx  sentence_start_idx  \
book_id             character_id
chi.086202240.clean 0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200

                                  sentence_end_idx adjectives_fashion  \
book_id             character_id
chi.086202240.clean 0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []

                                  character_start_idx  character_end_idx  \
book_id             character_id
chi.086202240.clean 0                          4230.0             4231.0
                    0                          4209.0             4210.0
                    0                          4254.0             4255.0
                    0                          4154.0             4156.0
                    0                          4334.0             4336.0

                                 gender_local_pron all_genders  \
book_id             character_id
chi.086202240.clean 0                         None        None
                    0                         None        None
                    0                         None        None
                    0                         None        None
                    0                         None        None

                                 gender_dep_pron  \
book_id             character_id
chi.086202240.clean 0                       None
                    0                       None
                    0                       None
                    0                       None
                    0                       None

                                                                    adjectives_char  \
book_id             character_id
chi.086202240.clean 0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...

                                 gender_booknlp  inferreddate  decade
book_id             character_id
chi.086202240.clean 0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0

In [55]:
df_clean["adj_text"] = df_clean["adjectives_fashion"].apply(
    lambda x: " ".join(x) if isinstance(x, list) else ""
)

/var/folders/4d/nr8gnznj18l258nbyjh5vtp40000gn/T/ipykernel_5870/1331316837.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["adj_text"] = df_clean["adjectives_fashion"].apply(

In [98]:
import pandas as pd

def get_error_dataframe_with_metadata(model, split, sentence_metadata):
    """
    Build a DataFrame of prediction errors with optional metadata.

    Parameters
    ----------
    model : trained classifier
    split : list/array of indices into features array (0..len(features)-1)
    sentence_metadata : pd.Series of strings (indexed by the original dataset)

    Returns
    -------
    pd.DataFrame with columns:
        - index_in_split
        - index_in_dataset
        - true_label
        - predicted_label
        - error_type
        - tokens
        - num_tokens
        - metadata
    """

    # Get features and labels for the selected rows
    genders_split, features_split = get_features(split)

    # Vectorize
    X = encoder.transform(features_split)
    y_true = le.transform(genders_split)
    y_pred = model.predict(X)

    # Decode labels
    true_labels = le.inverse_transform(y_true)
    pred_labels = le.inverse_transform(y_pred)

    rows = []

    for row_idx, (t_true, t_pred) in enumerate(zip(true_labels, pred_labels)):
        if t_true != t_pred:
            # original_index = split[row_idx]  # index in the original dataset
            original_index = orig_indices[split[row_idx]]  # map back to original df
            # row = sentence_metadata[original_index]
            row = sentence_metadata.loc[original_index]

            print(type(sentence_metadata.loc[original_index, 'adjectives_fashion']))
            print(sentence_metadata.loc[original_index, 'adjectives_fashion'])



            rows.append({
                "index_in_split": split[row_idx],
                "index_in_dataset": original_index,
                "true_label": t_true,
                "predicted_label": t_pred,
                "error_type": (
                    "False Positive" if t_pred != t_true and t_pred == le.classes_[1]
                    else "False Negative"
                ),
                "tokens": features_split[row_idx],
                "num_tokens": len(features_split[row_idx]),
                # Safely get the sentence string from Series
                # "metadata": sentence_metadata.iloc[original_index][0],
                # "term": sentence_metadata.iloc[original_index][1],
                # "adj_fashion": sentence_metadata.iloc[original_index][2],
                # "adj_char": sentence_metadata.iloc[original_index][3],
                # "metadata": row["sentence"],
                # "term": row["term"],
                "adj_fashion": row["adjectives_fashion"],
                "adj_char": row["adjectives_char"],
#                 "tokens": features_split[row_idx],
#                 "num_tokens": len(features_split[row_idx]),
#                 "metadata": sentence_metadata.loc[original_index]
                "metadata": sentence_metadata.loc[original_index, "sentence"],


                "term": sentence_metadata.loc[original_index, "term"],
                "adj_fashion": sentence_metadata.loc[original_index, "adjectives_fashion"],
                "adj_character": sentence_metadata.loc[original_index, "adjectives_char"]





            })

    df_rows = pd.DataFrame(rows)
    return df_rows

In [109]:
# Access each field safely
def safe_get_value(df, index, column):
    value = df.loc[index, column]
    if isinstance(value, pd.Series):
        return value.iloc[0]
    return value




def get_error_dataframe_with_metadata(model, split, sentence_metadata):

    # Get features and labels for the selected rows
    genders_split, features_split = get_features(split)

    # Vectorize
    X = encoder.transform(features_split)
    y_true = le.transform(genders_split)
    y_pred = model.predict(X)

    # Decode labels
    true_labels = le.inverse_transform(y_true)
    pred_labels = le.inverse_transform(y_pred)

    rows = []




    for row_idx, (t_true, t_pred) in enumerate(zip(true_labels, pred_labels)):
        if t_true != t_pred:
            original_index = orig_indices[split[row_idx]]

            metadata_val = safe_get_value(sentence_metadata, original_index, 'sentence')
            term_val = safe_get_value(sentence_metadata, original_index, 'term')
            adj_fashion_val = safe_get_value(sentence_metadata, original_index, 'adjectives_fashion')
            adj_char_val = safe_get_value(sentence_metadata, original_index, 'adjectives_char')

            rows.append({
                "index_in_split": split[row_idx],
                "index_in_dataset": original_index,
                "true_label": t_true,
                "predicted_label": t_pred,
                "error_type": (
                    "False Positive" if t_pred == le.classes_[1]
                    else "False Negative"
                ),
                "tokens": features_split[row_idx],
                "num_tokens": len(features_split[row_idx]),
                "metadata": metadata_val,
                "term": term_val,
                "adj_fashion": adj_fashion_val,
                "adj_char": adj_char_val,
            })
    return pd.DataFrame(rows)

In [110]:
sentence_metadata = df_clean[['sentence','term','adjectives_fashion','adjectives_char']]

In [111]:
print(type(sentence_metadata))

<class 'pandas.core.frame.DataFrame'>

In [112]:
sentence_metadata = sentence_metadata.sort_index()

In [113]:
# sentence_metadata = sentence_metadata.reset_index(drop=True)

In [114]:
df_new = get_error_dataframe_with_metadata(model, split, sentence_metadata)

In [116]:
# print(df_new)

In [119]:
df_new.to_csv('df_dec16_errors_fixed.csv')

In [120]:
df_new.head(20)

,index_in_split,index_in_dataset,true_label,predicted_label,error_type,tokens,num_tokens,metadata,term,adj_fashion,adj_char
0,8,"(chi.086834615.clean, 542)",female,male,False Positive,"[term_fur, adj_f_fine, adj_c_excited, adj_c_ho...",7,"Then, almost as a \ndog would have done, and a...",fur,[fine],"[excited, homeless, unconscious, familiar, old]"
1,15,"(chi.086866298.clean, 124)",female,male,False Positive,"[term_vest, adj_f_white, adj_c_ignorant, adj_c...",6,When it \nrained the babies sheltered under th...,coat,[soft],"[ignorant, ravenous, terrified, little]"
2,17,"(chi.086866298.clean, 125)",female,male,False Positive,"[term_vest, adj_f_warm, adj_c_young, adj_c_old...",10,"One was Mutch, a veteran of four seasons, \nwi...",fur,[brown],"[young, old, little, tired, about, first, soli..."
3,20,"(chi.086866298.clean, 149)",female,male,False Positive,"[term_coat, adj_f_black, adj_c_dizzy, adj_c_bu...",9,"She had a foam white vest and \nsocks, but the...",vest,[white],"[dizzy, burnt, reluctant, tired, better, thin,..."
4,23,"(chi.086866298.clean, 161)",female,male,False Positive,"[term_tail, adj_f_stumpy, adj_c_wary, adj_c_hu...",6,"Then \nshe buttoned down her stumpy tail, and ...",tail,[stumpy],"[wary, hungry, tired, quick]"
5,40,"(coo.31924002898983.clean, 37)",female,male,False Positive,"[term_fur, adj_f_own, adj_c_little, adj_c_snug]",4,She makes a little hollow in the earth and lin...,fur,[own],"[little, snug]"
6,175,"(coo.31924013221886.clean, 1909)",female,male,False Positive,"[term_clothes, adj_f_frumpish, adj_c_disappoin...",3,They will look absurd with her frumpish \nclot...,clothes,[frumpish],[disappointed]
7,176,"(coo.31924013221886.clean, 180)",female,male,False Positive,"[term_hat, adj_f_new, adj_c_dear]",3,"“]ehoshaphat!” said Chris, threw her new hat i...",hat,[new],[dear]
8,182,"(coo.31924013221894.clean, 162)",female,male,False Positive,"[term_clothes, adj_f_own, adj_f_clean, adj_f_t...",48,"she asked a little later, when the big clothes...",clothes,"[big, full]","[asleep, ashamed, ready, blind, careful, young..."
9,188,"(coo.31924013221894.clean, 960)",male,female,False Negative,"[term_bag, adj_f_big, adj_c_cheerful, adj_c_ha...",6,On the front steps they saw one small and one ...,leather,"[large, small]","[cheerful, haired, fair, young]"
10,207,"(coo.31924013231265.clean, 3211)",male,female,False Negative,"[term_kerchief, adj_f_red, adj_f_colourless, a...",8,With that tall silk hat of his which \nsome pa...,silk,[tall],"[ill, generous, blind, reticent, blind]"
11,209,"(coo.31924013231265.clean, 1445)",female,male,False Positive,"[term_cap, adj_f_dirty, adj_c_holy, adj_c_holy...",13,Thereupon she shut the door and went back into...,cap,[dirty],"[Holy, Holy, dead, asleep, Holy, Holy, Holy, H..."
12,231,"(coo.31924013237833.clean, 219)",male,female,False Negative,"[term_clothes, adj_f_huge, adj_f_stiff, adj_c_...",104,"Seeing Joan watching \nhim with sympathy, afte...",skirts,[],"[anxious, unapproachable, innocent, breathless..."
13,248,"(coo.31924013237874.clean, 877)",female,male,False Positive,"[term_coat, adj_f_neat, adj_c_frettin’, adj_c_...",15,As the young woman in her neat coat and skirt ...,coat,[neat],"[frettin’, young, young, young, young, young, ..."
14,249,"(coo.31924013237874.clean, 186)",female,male,False Positive,"[term_hat, adj_f_dismal, adj_f_bound, adj_c_yo...",21,"“Proud, ” said Mr. Thacker, repeating his favo...",boots,[],"[young, awake, dear, ill, dear, Radical, able,..."
15,261,"(coo.31924013237874.clean, 194)",male,female,False Negative,"[term_bag, adj_f_simple, adj_c_young, adj_c_mo...",22,It was a relief for Allington to escape to his...,bag,[simple],"[young, modest, ashamed, unprepared, sure, aff..."
16,262,"(coo.31924013237874.clean, 0)",male,female,False Negative,"[term_shoes, adj_f_little, adj_c_sure, adj_c_k...",52,Allington suddenly saw his companion colour \n...,hat,"[black, soft]","[sure, keen, cold, farther, older, afraid, ove..."
17,297,"(coo.31924013237999.clean, 200)",female,male,False Positive,"[term_hat, adj_f_fashionable, adj_c_willing, a...",7,"In a moment two attendants had seized her, rea...",hat,[fashionable],"[willing, keen, real, insane, dead]"
18,611,"(coo.31924013471804.clean, 761)",male,female,False Negative,"[term_stockings, adj_f_black, adj_c_old, adj_c...",26,He is of what is called the old \nschool — a p...,breeches,[],"[old, cool, old, old, old, sure, worthy, old, ..."
19,613,"(coo.31924013471804.clean, 0)",male,female,False Negative,"[term_cuffs, adj_f_large, adj_c_dear, adj_c_ha...",374,"Is a new dress, a new custom, a new singer, a ...",dress,[new],"[dear, hard, eager, little, old, poor, suscept..."

In [122]:
# Assuming df_errors is your DataFrame
df_errors = df_new
# First, explode the list-like columns into separate rows
df_fashion = df_errors.explode('adj_fashion')
df_term = df_errors.explode('term')
df_char = df_errors.explode('adj_char')

# Function to get most common items for a given error_type and column
def most_common_by_error_type(df, error_type, column, top_n=10):
    filtered = df[df['error_type'] == error_type]
    counts = filtered[column].value_counts()
    return counts.head(top_n)

# Example: top 10 adjectives fashion for False Positives
fp_fashion = most_common_by_error_type(df_fashion, 'False Positive', 'adj_fashion')
print("Top adjectives (fashion) for False Positives:")
print(fp_fashion)

# Example: top 10 adjectives fashion for False Negatives
fn_fashion = most_common_by_error_type(df_fashion, 'False Negative', 'adj_fashion')
print("\nTop adjectives (fashion) for False Negatives:")
print(fn_fashion)

# Similarly for term column
fp_terms = most_common_by_error_type(df_term, 'False Positive', 'term')
fn_terms = most_common_by_error_type(df_term, 'False Negative', 'term')

print("\nTop terms for False Positives:")
print(fp_terms)

print("\nTop terms for False Negatives:")
print(fn_terms)

# And for adj_char column
fp_adj_char = most_common_by_error_type(df_char, 'False Positive', 'adj_char')
fn_adj_char = most_common_by_error_type(df_char, 'False Negative', 'adj_char')

print("\nTop adjectives (character) for False Positives:")
print(fp_adj_char)

print("\nTop adjectives (character) for False Negatives:")
print(fn_adj_char)

Top adjectives (fashion) for False Positives:
adj_fashion
black     174
white     171
own        95
old        88
best       84
new        83
long       82
little     80
blue       78
brown      73
Name: count, dtype: int64

Top adjectives (fashion) for False Negatives:
adj_fashion
white     192
little    127
black     114
long       77
blue       72
red        51
new        49
old        39
own        37
best       25
Name: count, dtype: int64

Top terms for False Positives:
term
clothes     424
hat         368
coat        208
dress       172
hands       138
cap         131
hand        121
shoes       110
garments     92
boots        83
Name: count, dtype: int64

Top terms for False Negatives:
term
dress      212
clothes    167
hat        158
hands      111
gown       100
coat        84
shoes       77
cap         60
robe        52
silk        49
Name: count, dtype: int64

Top adjectives (character) for False Positives:
adj_char
old       4637
sure      4340
young     4273
glad      3427
afraid    3409
little    2455
sorry     2238
dear      2214
able      2175
good      1733
Name: count, dtype: int64

Top adjectives (character) for False Negatives:
adj_char
sure      4058
glad      3267
afraid    3179
young     2966
little    2842
old       2807
dear      2351
sorry     2085
happy     1750
able      1681
Name: count, dtype: int64

In [123]:
# Assuming your code above already runs and you have:
# fp_fashion, fn_fashion, fp_terms, fn_terms, fp_adj_char, fn_adj_char

# Function to get unique features between FP and FN
def unique_features(fp_series, fn_series):
    fp_set = set(fp_series.index)
    fn_set = set(fn_series.index)

    unique_fp = fp_set - fn_set
    unique_fn = fn_set - fp_set

    # Return counts for the unique features only
    unique_fp_counts = fp_series[fp_series.index.isin(unique_fp)]
    unique_fn_counts = fn_series[fn_series.index.isin(unique_fn)]

    return unique_fp_counts, unique_fn_counts

# Fashion adjectives
unique_fp_fashion, unique_fn_fashion = unique_features(fp_fashion, fn_fashion)
print("Unique FP fashion adjectives:")
print(unique_fp_fashion)
print("\nUnique FN fashion adjectives:")
print(unique_fn_fashion)

# Terms
unique_fp_terms, unique_fn_terms = unique_features(fp_terms, fn_terms)
print("\nUnique FP terms:")
print(unique_fp_terms)
print("\nUnique FN terms:")
print(unique_fn_terms)

# Character adjectives
unique_fp_adj_char, unique_fn_adj_char = unique_features(fp_adj_char, fn_adj_char)
print("\nUnique FP character adjectives:")
print(unique_fp_adj_char)
print("\nUnique FN character adjectives:")
print(unique_fn_adj_char)

Unique FP fashion adjectives:
adj_fashion
brown    73
Name: count, dtype: int64

Unique FN fashion adjectives:
adj_fashion
red    51
Name: count, dtype: int64

Unique FP terms:
term
hand        121
garments     92
boots        83
Name: count, dtype: int64

Unique FN terms:
term
gown    100
robe     52
silk     49
Name: count, dtype: int64

Unique FP character adjectives:
adj_char
good    1733
Name: count, dtype: int64

Unique FN character adjectives:
adj_char
happy    1750
Name: count, dtype: int64

In [124]:
# Total counts across all errors
fashion_counts = df_fashion['adj_fashion'].value_counts()
char_counts = df_char['adj_char'].value_counts()
term_counts = df_term['term'].value_counts()

print("Fashion adjective importance (by frequency):")
print(fashion_counts.head(10))

print("\nCharacter adjective importance (by frequency):")
print(char_counts.head(10))

print("\nTerm importance (by frequency):")
print(term_counts.head(10))

Fashion adjective importance (by frequency):
adj_fashion
white     363
black     288
little    207
long      159
blue      150
own       132
new       132
old       127
red       120
best      109
Name: count, dtype: int64

Character adjective importance (by frequency):
adj_char
sure      8398
old       7444
young     7239
glad      6694
afraid    6588
little    5297
dear      4565
sorry     4323
able      3856
happy     3246
Name: count, dtype: int64

Term importance (by frequency):
term
clothes    591
hat        526
dress      384
coat       292
hands      249
cap        191
shoes      187
hand       169
gown       167
cloak      128
Name: count, dtype: int64

In [125]:
importances = pd.Series(clf.feature_importances_, index=vectorizer.get_feature_names_out())
top_importances = importances.sort_values(ascending=False).head(20)

print("Top 20 important features for predicting FP:")
print(top_importances)

NameError: name 'clf' is not defined

In [11]:
df_new.to_csv("FPFN_error_dataset_dec16_wadjs.csv", index=False)

NameError: name 'df_new' is not defined

In [6]:
first_val = df['sentence'].iloc[0]
print(first_val)
print(type(first_val))

NameError: name 'df' is not defined

In [7]:
df[['sentence']]

NameError: name 'df' is not defined

In [8]:
# def get_error_dataframe_with_metadata(model, split, sentence_metadata):
#     """
#     sentence_metadata: pd.Series of strings, indexed by original df index
#     """
#     genders_split, features_split = get_features(split)
#     X = encoder.transform(features_split)
#     y_true = le.transform(genders_split)
#     y_pred = model.predict(X)
#
#     true_labels = le.inverse_transform(y_true)
#     pred_labels = le.inverse_transform(y_pred)
#
#     sentence_metadata = sentence_metadata.sort_index()
#
#
#     rows = []
#     for row_idx, (t_true, t_pred) in enumerate(zip(true_labels, pred_labels)):
#         if t_true != t_pred:
#             original_index = orig_indices[split[row_idx]]  # map back to original df
#             rows.append({
#                 "index_in_split": row_idx,
#                 "index_in_dataset": original_index,
#                 "true_label": t_true,
#                 "predicted_label": t_pred,
#                 "error_type": (
#                     "False Positive" if t_pred != t_true and t_pred == le.classes_[1]
#                     else "False Negative"
#                 ),
#                 "tokens": features_split[row_idx],
#                 "num_tokens": len(features_split[row_idx]),
#                 "metadata": sentence_metadata.loc[original_index]
#             })
#
#     return pd.DataFrame(rows)

In [60]:
# sentence_series = df['sentence']
#
# get_error_dataframe_with_metadata(model, split, sentence_series)

,index_in_split,index_in_dataset,true_label,predicted_label,error_type,tokens,num_tokens,metadata
0,8,"(chi.086834615.clean, 542)",female,male,False Positive,[term_fur],1,book_id character_id chi.08683461...
1,14,"(chi.086866298.clean, 124)",female,male,False Positive,[term_vest],1,book_id character_id chi.08686629...
2,16,"(chi.086866298.clean, 125)",female,male,False Positive,[term_vest],1,book_id character_id chi.08686629...
3,19,"(chi.086866298.clean, 149)",female,male,False Positive,[term_coat],1,book_id character_id chi.08686629...
4,22,"(chi.086866298.clean, 161)",female,male,False Positive,[term_tail],1,book_id character_id chi.08686629...
...,...,...,...,...,...,...,...,...
12507,49239,"(wu.89105690127.clean, 86)",female,male,False Positive,[term_clothes],1,book_id character_id wu.89105690...
12508,49256,"(yale.39002004961885.clean, 144)",female,male,False Positive,[term_clothes],1,book_id character_id yale.3...
12509,49263,"(yale.39002006645270.clean, 4032)",male,female,False Negative,[term_robe],1,book_id character_id yale.3...
12510,49273,"(yale.39002030972518.clean, 11709)",male,female,False Negative,[term_slippers],1,book_id character_id yale.3...
12511,49279,"(yale.39002030972518.clean, 738)",male,female,False Negative,[term_gown],1,book_id character_id yale.3...

In [61]:
type(sentence_series)

pandas.core.series.Series

In [62]:
sentence_series

book_id                    character_id
chi.086202240.clean        0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                                                                 ...
yale.39002030973185.clean  0               Might the small green trunk be sent immediatel...
                           5597            Might I take the portmanteau in one jinrikisha...
                           0               Might I take the portmanteau in one jinrikisha...
                           0               Might I take the portmanteau in one jinrikisha...
                           0               Might I take the portmanteau in one jinrikisha...
Name: sentence, Length: 17268825, dtype: object

In [63]:
df['sentence']

book_id                    character_id
chi.086202240.clean        0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                           0               How long I remained in shorts I cannot novembe...
                                                                 ...
yale.39002030973185.clean  0               Might the small green trunk be sent immediatel...
                           5597            Might I take the portmanteau in one jinrikisha...
                           0               Might I take the portmanteau in one jinrikisha...
                           0               Might I take the portmanteau in one jinrikisha...
                           0               Might I take the portmanteau in one jinrikisha...
Name: sentence, Length: 17268825, dtype: object

In [64]:
df.head()

                                  mention_id    term  \
book_id             character_id
chi.086202240.clean 0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts
                    0               17370773  shorts

                                                                           sentence  \
book_id             character_id
chi.086202240.clean 0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...
                    0             How long I remained in shorts I cannot novembe...

                                  start_idx  end_idx  sentence_start_idx  \
book_id             character_id
chi.086202240.clean 0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200
                    0                    23       29                4200

                                  sentence_end_idx adjectives_fashion  \
book_id             character_id
chi.086202240.clean 0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []
                    0                         4409                 []

                                  character_start_idx  character_end_idx  \
book_id             character_id
chi.086202240.clean 0                          4230.0             4231.0
                    0                          4209.0             4210.0
                    0                          4254.0             4255.0
                    0                          4154.0             4156.0
                    0                          4334.0             4336.0

                                 gender_local_pron all_genders  \
book_id             character_id
chi.086202240.clean 0                         None        None
                    0                         None        None
                    0                         None        None
                    0                         None        None
                    0                         None        None

                                 gender_dep_pron  \
book_id             character_id
chi.086202240.clean 0                       None
                    0                       None
                    0                       None
                    0                       None
                    0                       None

                                                                    adjectives_char  \
book_id             character_id
chi.086202240.clean 0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...
                    0             [more, content, gay, aged, faithful, astonishe...

                                 gender_booknlp  inferreddate  decade
book_id             character_id
chi.086202240.clean 0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0
                    0                he/him/his        1886.0   188.0

In [66]:
print(len(features), len(genders), len(decades), len(orig_indices))

250391 250391 250391 250391

In [65]:
print(split[:10])
print(max(split), len(split))

[0 1 2 3 4 5 6 7 8 9]
250390 49281

In [12]:
# =========================
# 4️⃣ Train models per decade
# =========================
unique_decades = sorted(set(decades))
models = []

for decade in unique_decades:
    print(f"Training model for decade {decade}")
    split = np.where(np.array(decades) == decade)[0]
    model = train_classifier(split)
    models.append(model)

# =========================
# 5️⃣ Build combined error DataFrame
# =========================
all_error_dfs = []

for i, decade in enumerate(unique_decades):
    split = np.where(np.array(decades) == decade)[0]
    model = models[i]  # ✅ select the model for this decade
    df_errors = get_error_dataframe_with_metadata(model, split, df_clean[['sentence','term', 'adjectives_fashion']])
    df_errors["decade"] = decade  # optional: add decade column
    all_error_dfs.append(df_errors)

# Combine all decades into one DataFrame
combined_errors = pd.concat(all_error_dfs, ignore_index=True)
print(combined_errors.head())
print("Total errors:", len(combined_errors))

NameError: name 'decades' is not defined